version: "3.8"
services:
  app:
    build:
      context: . # The path of the Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    working_dir: /usr/src/app
    environment:
      SERVICE_NAME: filepodapp
      DB_CONNECTION: mysql
      DB_DRIVER: mysql
      DB_HOST: db
      DB_PORT: 3306
    networks:
      - app_network

  nginx:
    build:
      context: ./docker-nginx/. # The path of the Dockerfile
    volumes:
      - "./public:/usr/src/app/public"
    environment:
      NGINX_FPM_HOST: app
      NGINX_ROOT: /usr/src/app/public
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - app_network

  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "33066:3306"
    volumes:
      - "./storage/db-data:/var/lib/mysql"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
